plugins {
    id 'com.android.application'
}

android {
    namespace 'com.reqlens.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.reqlens.app'
        minSdk 26
        targetSdk 36
        versionCode 7
        versionName '0.7.0-alpha'
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'com.zaneschepke:hevtunnel:1.0.1'
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.78.1'
}
