package com.reqlens.app;
import android.app.*;import android.graphics.Typeface;import android.os.Bundle;import android.widget.*;import org.json.*;import java.net.*;import java.util.*;
public final class BodyToolsActivity extends Activity{
 public static String pendingBody="",resultBody=null;private EditText input,output;
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Structured Body Tools");t.setTextSize(22);r.addView(t);input=new EditText(this);input.setMinLines(6);input.setTypeface(Typeface.MONOSPACE);input.setText(pendingBody);pendingBody="";r.addView(input);LinearLayout row=new LinearLayout(this);add(row,"JSON",v->json());add(row,"FORM",v->form());add(row,"GRAPHQL",v->graphql());add(row,"MULTIPART",v->multipart());r.addView(row);output=new EditText(this);output.setMinLines(8);output.setTypeface(Typeface.MONOSPACE);r.addView(output);Button use=new Button(this);use.setText("USE OUTPUT IN REPEATER");use.setOnClickListener(v->{resultBody=output.getText().toString();finish();});r.addView(use);setContentView(r);}
 private void add(LinearLayout r,String s,android.view.View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setOnClickListener(l);r.addView(b,new LinearLayout.LayoutParams(0,48,1));}
 private void json(){try{String q=input.getText().toString().trim();output.setText(q.startsWith("[")?new JSONArray(q).toString(2):new JSONObject(q).toString(2));}catch(Exception e){output.setText("Invalid JSON: "+e.getMessage());}}
 private void form(){try{StringBuilder s=new StringBuilder();for(String part:input.getText().toString().split("&")){int i=part.indexOf('=');String k=i<0?part:part.substring(0,i),v=i<0?"":part.substring(i+1);s.append(URLDecoder.decode(k,"UTF-8")).append(" = ").append(URLDecoder.decode(v,"UTF-8")).append('\n');}output.setText(s.toString());}catch(Exception e){output.setText("Invalid form body");}}
 private void graphql(){try{JSONObject o=new JSONObject(input.getText().toString());output.setText("query:\n"+o.optString("query","")+"\n\nvariables:\n"+(o.optJSONObject("variables")!=null?o.optJSONObject("variables").toString(2):"{}"));}catch(Exception e){output.setText("Expected GraphQL JSON body with query/variables");}}
 private void multipart(){String boundary="----ReqLensBoundary"+System.currentTimeMillis();StringBuilder s=new StringBuilder();for(String line:input.getText().toString().split("\\r?\\n")){int i=line.indexOf('=');if(i<=0)continue;String k=line.substring(0,i).trim(),v=line.substring(i+1);s.append("--").append(boundary).append("\r\nContent-Disposition: form-data; name=\"").append(k).append("\"\r\n\r\n").append(v).append("\r\n");}s.append("--").append(boundary).append("--\r\n");output.setText("Content-Type: multipart/form-data; boundary="+boundary+"\n\n"+s);}
}
