package com.reqlens.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.net.URL;import java.util.*;
public final class DashboardActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);ProjectRepository.init(this);ProxyHistoryRepository.init(this);BrowserHistoryRepository.init(this);setContentView(ui());}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(20,20,20,20);TextView t=new TextView(this);t.setText("ReqLens Dashboard");t.setTextSize(24);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);TextView p=new TextView(this);p.setText("Active project: "+ProjectRepository.active().name);p.setPadding(0,8,0,12);r.addView(p);TextView stats=new TextView(this);stats.setTextSize(18);stats.setText(summary());r.addView(stats);Button proxy=b("PROXY HISTORY",ProxyHistoryActivity.class);r.addView(proxy);Button browser=b("BROWSER HISTORY",BrowserHistoryActivity.class);r.addView(browser);Button diag=b("DIAGNOSTICS",DiagnosticsActivity.class);r.addView(diag);Button projects=b("PROJECTS",ProjectsActivity.class);r.addView(projects);Button export=new Button(this);export.setText("EXPORT CURRENT PROJECT");export.setOnClickListener(v->exportWorkspace());r.addView(export);return r;}

 private void exportWorkspace(){try{java.io.File f=ExportManager.writeText(this,"reqlens-project-"+System.currentTimeMillis()+".json",WorkspaceExporter.currentProject(SuiteSettings.redact(this)));startActivity(Intent.createChooser(ExportManager.share(this,f,"application/json"),"Export ReqLens project"));}catch(Exception e){Toast.makeText(this,"Export failed: "+e.getMessage(),Toast.LENGTH_SHORT).show();}}
 private String summary(){List<ProxyEvent>x=ProxyHistoryRepository.snapshotActiveProject();HashSet<String>hosts=new HashSet<>();int http=0,tls=0,err=0;long bytes=0;for(ProxyEvent e:x){if(!e.host.isEmpty())hosts.add(e.host);if("HTTP".equals(e.protocol))http++;if("TLS".equals(e.protocol))tls++;if(e.status>=400)err++;bytes+=Math.max(0,e.bytes);}return "Events: "+x.size()+"\nHosts: "+hosts.size()+"\nHTTP: "+http+"\nTLS metadata: "+tls+"\nHTTP errors: "+err+"\nObserved bytes: "+bytes+"\nBrowser requests: "+BrowserHistoryRepository.size();}
 private Button b(String s,Class<?>c){Button b=new Button(this);b.setText(s);b.setOnClickListener(v->startActivity(new Intent(this,c)));return b;}
}
