package com.reqlens.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;
public final class InterceptActivity extends Activity{
 private final ArrayList<InterceptController.Item>items=new ArrayList<>();private ArrayAdapter<InterceptController.Item>a;private TextView state;private EditText host,method,ctype,search;private final ExecutorService exec=Executors.newSingleThreadExecutor();
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());refresh();}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Intercept Queue");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);state=new TextView(this);r.addView(state);
  LinearLayout f1=new LinearLayout(this);host=e("Host/path");method=e("Method");ctype=e("Content-Type");f1.addView(host,new LinearLayout.LayoutParams(0,48,2));f1.addView(method,new LinearLayout.LayoutParams(0,48,1));f1.addView(ctype,new LinearLayout.LayoutParams(0,48,1));Button apply=new Button(this);apply.setText("APPLY");apply.setOnClickListener(v->{InterceptController.setFilters(host.getText().toString(),method.getText().toString(),ctype.getText().toString());refresh();});f1.addView(apply,new LinearLayout.LayoutParams(100,48));r.addView(f1);
  LinearLayout srow=new LinearLayout(this);search=e("Search queue");srow.addView(search,new LinearLayout.LayoutParams(0,48,1));Button sf=new Button(this);sf.setText("SEARCH");sf.setOnClickListener(v->refresh());srow.addView(sf,new LinearLayout.LayoutParams(100,48));r.addView(srow);
  LinearLayout row=new LinearLayout(this);add(row,"TOGGLE",v->{InterceptController.setEnabled(!InterceptController.isEnabled());refresh();});add(row,"FORWARD ALL",v->forwardAll());add(row,"DROP ALL",v->dropAll());add(row,"AUDIT",v->startActivity(new Intent(this,InterceptAuditActivity.class)));r.addView(row);
  ListView l=new ListView(this);a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,items);l.setAdapter(a);l.setOnItemClickListener((p,v,pos,id)->actions(items.get(pos)));r.addView(l,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private EditText e(String h){EditText x=new EditText(this);x.setHint(h);x.setSingleLine(true);return x;}private void add(LinearLayout row,String txt,View.OnClickListener l){Button b=new Button(this);b.setText(txt);b.setOnClickListener(l);row.addView(b,new LinearLayout.LayoutParams(0,48,1));}
 private void actions(InterceptController.Item i){new AlertDialog.Builder(this).setTitle(i.request.method+" "+i.request.url).setItems(new String[]{"Forward now","Edit in Repeater","Edit & forward","Drop"},(d,w)->{if(w==0)forward(i,i.request,"FORWARD");else if(w==1){InterceptAuditRepository.add("REPEATER",i.request);RepeaterActivity.pending=RequestExecutor.cloneRequest(i.request);startActivity(new Intent(this,RepeaterActivity.class));}else if(w==2)editForward(i);else{InterceptAuditRepository.add("DROP",i.request);InterceptController.remove(i.id);refresh();}}).show();}
 private void editForward(InterceptController.Item item){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText m=new EditText(this);m.setText(item.request.method);x.addView(m);EditText u=new EditText(this);u.setText(item.request.url);x.addView(u);EditText b=new EditText(this);b.setText(item.request.requestBody);b.setHint("Body");b.setMinLines(3);x.addView(b);new AlertDialog.Builder(this).setTitle("Edit before forward").setView(x).setPositiveButton("FORWARD",(d,w)->{RequestRecord q=RequestExecutor.cloneRequest(item.request);q.method=m.getText().toString().trim().toUpperCase(Locale.ROOT);q.url=u.getText().toString().trim();q.requestBody=b.getText().toString();forward(item,q,"EDIT+FORWARD");}).setNegativeButton("CANCEL",null).show();}
 private void forward(InterceptController.Item item,RequestRecord q,String action){InterceptController.remove(item.id);InterceptAuditRepository.add(action,q);exec.submit(()->{RequestRecord rr=RequestExecutor.execute(q,false);ProxyHistoryRepository.addHttp(rr,"intercept");runOnUiThread(()->refresh());});}
 private void forwardAll(){List<InterceptController.Item>x=InterceptController.snapshot();for(InterceptController.Item i:x)forward(i,i.request,"FORWARD_ALL");Toast.makeText(this,"Forwarding "+x.size()+" queued requests",Toast.LENGTH_SHORT).show();}
 private void dropAll(){List<InterceptController.Item>x=InterceptController.snapshot();for(InterceptController.Item i:x)InterceptAuditRepository.add("DROP_ALL",i.request);InterceptController.clear();refresh();}
 private void refresh(){state.setText("Intercept: "+(InterceptController.isEnabled()?"ON":"OFF")+" • Queue "+InterceptController.snapshot().size()+" • "+InterceptController.filters());String q=search==null?"":search.getText().toString().trim().toLowerCase(Locale.ROOT);items.clear();for(InterceptController.Item i:InterceptController.snapshot()){String h=(i.request.method+" "+i.request.url+" "+i.request.requestBody).toLowerCase(Locale.ROOT);if(q.isEmpty()||h.contains(q))items.add(i);}if(a!=null)a.notifyDataSetChanged();}
 @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
