package com.reqlens.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;
public final class InterceptActivity extends Activity{
 private final ArrayList<InterceptController.Item>items=new ArrayList<>();private ArrayAdapter<InterceptController.Item>a;private TextView state;private EditText host,method;private final ExecutorService exec=Executors.newSingleThreadExecutor();
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());refresh();}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Intercept Queue");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);state=new TextView(this);r.addView(state);LinearLayout filters=new LinearLayout(this);host=new EditText(this);host.setHint("Host/path filter");filters.addView(host,new LinearLayout.LayoutParams(0,48,2));method=new EditText(this);method.setHint("Method");filters.addView(method,new LinearLayout.LayoutParams(0,48,1));Button apply=new Button(this);apply.setText("APPLY");apply.setOnClickListener(v->{InterceptController.setFilters(host.getText().toString(),method.getText().toString());refresh();});filters.addView(apply,new LinearLayout.LayoutParams(100,48));r.addView(filters);LinearLayout row=new LinearLayout(this);Button toggle=new Button(this);toggle.setText("TOGGLE");toggle.setOnClickListener(v->{InterceptController.setEnabled(!InterceptController.isEnabled());refresh();});row.addView(toggle,new LinearLayout.LayoutParams(0,48,1));Button ref=new Button(this);ref.setText("REFRESH");ref.setOnClickListener(v->refresh());row.addView(ref,new LinearLayout.LayoutParams(0,48,1));Button drop=new Button(this);drop.setText("DROP ALL");drop.setOnClickListener(v->{InterceptController.clear();refresh();});row.addView(drop,new LinearLayout.LayoutParams(0,48,1));r.addView(row);ListView l=new ListView(this);a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,items);l.setAdapter(a);l.setOnItemClickListener((p,v,pos,id)->actions(items.get(pos)));r.addView(l,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private void actions(InterceptController.Item i){new AlertDialog.Builder(this).setTitle(i.request.method+" "+i.request.url).setItems(new String[]{"Forward now","Edit in Repeater","Edit & forward","Drop"},(d,w)->{if(w==0)forward(i,i.request);else if(w==1){RepeaterActivity.pending=RequestExecutor.cloneRequest(i.request);startActivity(new Intent(this,RepeaterActivity.class));}else if(w==2)editForward(i);else{InterceptController.remove(i.id);refresh();}}).show();}
 private void editForward(InterceptController.Item item){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText m=new EditText(this);m.setText(item.request.method);x.addView(m);EditText u=new EditText(this);u.setText(item.request.url);x.addView(u);EditText b=new EditText(this);b.setText(item.request.requestBody);b.setHint("Body");b.setMinLines(3);x.addView(b);new AlertDialog.Builder(this).setTitle("Edit before forward").setView(x).setPositiveButton("FORWARD",(d,w)->{RequestRecord q=RequestExecutor.cloneRequest(item.request);q.method=m.getText().toString().trim().toUpperCase(Locale.ROOT);q.url=u.getText().toString().trim();q.requestBody=b.getText().toString();forward(item,q);}).setNegativeButton("CANCEL",null).show();}
 private void forward(InterceptController.Item item,RequestRecord q){InterceptController.remove(item.id);exec.submit(()->{RequestRecord rr=RequestExecutor.execute(q,false);ProxyHistoryRepository.addHttp(rr,"intercept");runOnUiThread(()->{Toast.makeText(this,"Forwarded: "+rr.statusCode,Toast.LENGTH_SHORT).show();refresh();});});}
 private void refresh(){state.setText("Intercept: "+(InterceptController.isEnabled()?"ON":"OFF")+" • Queue "+InterceptController.snapshot().size()+" • "+InterceptController.filters());items.clear();items.addAll(InterceptController.snapshot());if(a!=null)a.notifyDataSetChanged();}
 @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
