package com.reqlens.app;
import org.json.*;import java.util.*;
public final class InterceptRule {
 public boolean enabled=true;public String group="default",matchMode="AND",hostContains="",method="",action="SET_HEADER",name="",value="";
 public boolean matches(RequestRecord r){if(!enabled)return false;boolean hasM=!method.isEmpty(),hasH=!hostContains.isEmpty();boolean mm=!hasM||method.equalsIgnoreCase(r.method),hm=!hasH||r.url.toLowerCase(Locale.ROOT).contains(hostContains.toLowerCase(Locale.ROOT));if("OR".equalsIgnoreCase(matchMode)&&hasM&&hasH)return mm||hm;return mm&&hm;}
 public void apply(RequestRecord r){if(!matches(r))return;try{if("SET_HEADER".equals(action)&&!name.trim().isEmpty())r.requestHeaders.put(name.trim(),value);else if("REMOVE_HEADER".equals(action)&&!name.trim().isEmpty())removeHeader(r,name.trim());else if("REPLACE_URL".equals(action)&&!name.isEmpty())r.url=r.url.replace(name,value);else if("REPLACE_BODY".equals(action)&&!name.isEmpty())r.requestBody=r.requestBody.replace(name,value);else if("REGEX_URL".equals(action)&&!name.isEmpty())r.url=r.url.replaceAll(name,value);else if("REGEX_BODY".equals(action)&&!name.isEmpty())r.requestBody=r.requestBody.replaceAll(name,value);else if("SET_QUERY".equals(action)&&!name.trim().isEmpty())r.url=setQuery(r.url,name.trim(),value);else if("JSON_SET".equals(action)&&!name.trim().isEmpty()){JSONObject o=new JSONObject(r.requestBody);o.put(name.trim(),parseValue(value));r.requestBody=o.toString();}}catch(Exception ignored){} }

 private static String setQuery(String raw,String key,String value)throws Exception{java.net.URL u=new java.net.URL(raw);LinkedHashMap<String,String>q=new LinkedHashMap<>();String query=u.getQuery();if(query!=null&&!query.isEmpty())for(String part:query.split("&")){int i=part.indexOf('=');String k=i<0?part:part.substring(0,i),v=i<0?"":part.substring(i+1);q.put(java.net.URLDecoder.decode(k,"UTF-8"),java.net.URLDecoder.decode(v,"UTF-8"));}q.put(key,value);StringBuilder z=new StringBuilder();for(Map.Entry<String,String>e:q.entrySet()){if(z.length()>0)z.append('&');z.append(java.net.URLEncoder.encode(e.getKey(),"UTF-8")).append('=').append(java.net.URLEncoder.encode(e.getValue(),"UTF-8"));}return new java.net.URI(u.getProtocol(),u.getUserInfo(),u.getHost(),u.getPort(),u.getPath(),z.toString(),u.getRef()).toString();}
 private static Object parseValue(String v){String x=v==null?"":v.trim();if("true".equalsIgnoreCase(x))return true;if("false".equalsIgnoreCase(x))return false;if("null".equalsIgnoreCase(x))return JSONObject.NULL;try{return x.contains(".")?Double.parseDouble(x):Long.parseLong(x);}catch(Exception e){return v;}}
 private static void removeHeader(RequestRecord r,String name){String hit=null;for(String k:r.requestHeaders.keySet())if(name.equalsIgnoreCase(k)){hit=k;break;}if(hit!=null)r.requestHeaders.remove(hit);}
 @Override public String toString(){return(enabled?"✓ ":"○ ")+"["+group+"] "+action+" • "+matchMode+" • "+(method.isEmpty()?"ANY":method)+" • "+(hostContains.isEmpty()?"all hosts":hostContains);}
}
