package com.reqlens.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;
public final class InterceptActivity extends Activity{
 private final ArrayList<InterceptController.Item>items=new ArrayList<>();private ArrayAdapter<InterceptController.Item>a;private TextView state;private final ExecutorService exec=Executors.newSingleThreadExecutor();
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());refresh();}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Intercept Queue");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);state=new TextView(this);r.addView(state);LinearLayout row=new LinearLayout(this);Button toggle=new Button(this);toggle.setText("TOGGLE INTERCEPT");toggle.setOnClickListener(v->{InterceptController.setEnabled(!InterceptController.isEnabled());refresh();});row.addView(toggle,new LinearLayout.LayoutParams(0,48,1));Button ref=new Button(this);ref.setText("REFRESH");ref.setOnClickListener(v->refresh());row.addView(ref,new LinearLayout.LayoutParams(0,48,1));r.addView(row);ListView l=new ListView(this);a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,items);l.setAdapter(a);l.setOnItemClickListener((p,v,pos,id)->actions(items.get(pos)));r.addView(l,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private void actions(InterceptController.Item i){new AlertDialog.Builder(this).setTitle(i.request.method+" "+i.request.url).setItems(new String[]{"Forward now","Send to Repeater","Drop"},(d,w)->{if(w==0){InterceptController.remove(i.id);exec.submit(()->{RequestRecord rr=RequestExecutor.execute(i.request,false);runOnUiThread(()->{Toast.makeText(this,"Forwarded: "+rr.statusCode,Toast.LENGTH_SHORT).show();refresh();});});}else if(w==1){RepeaterActivity.pending=RequestExecutor.cloneRequest(i.request);startActivity(new Intent(this,RepeaterActivity.class));}else{InterceptController.remove(i.id);refresh();}}).show();}
 private void refresh(){state.setText("Intercept: "+(InterceptController.isEnabled()?"ON":"OFF")+" • Queue "+InterceptController.snapshot().size());items.clear();items.addAll(InterceptController.snapshot());if(a!=null)a.notifyDataSetChanged();}
 @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
