package com.reqlens.app;
import android.app.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;
public final class IntruderActivity extends Activity{
 private final ExecutorService exec=Executors.newSingleThreadExecutor();private EditText method,url,headers,body,payloads;private TextView out;private volatile boolean stop;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Request Variations");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);TextView n=new TextView(this);n.setText("Authorized testing only. Use §FUZZ§ in URL/body/header values. Hard limit: 50 payloads, one worker, 4 requests/sec max. No credential-stuffing automation.");r.addView(n);method=new EditText(this);method.setHint("Method");method.setText("GET");r.addView(method);url=new EditText(this);url.setHint("https://example.test/item?id=§FUZZ§");r.addView(url);headers=new EditText(this);headers.setHint("Headers, one per line");headers.setMinLines(2);r.addView(headers);body=new EditText(this);body.setHint("Body (optional)");body.setMinLines(2);r.addView(body);payloads=new EditText(this);payloads.setHint("Payloads, one per line (max 50)");payloads.setMinLines(4);r.addView(payloads);LinearLayout row=new LinearLayout(this);Button run=new Button(this);run.setText("RUN VARIATIONS");run.setOnClickListener(v->run());row.addView(run,new LinearLayout.LayoutParams(0,48,1));Button st=new Button(this);st.setText("STOP");st.setOnClickListener(v->stop=true);row.addView(st,new LinearLayout.LayoutParams(0,48,1));r.addView(row);out=new TextView(this);out.setTypeface(Typeface.MONOSPACE);out.setTextIsSelectable(true);ScrollView s=new ScrollView(this);s.addView(out);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private void run(){String baseUrl=url.getText().toString().trim(),baseBody=body.getText().toString(),baseHeaders=headers.getText().toString(),baseMethod=method.getText().toString().trim().toUpperCase(Locale.ROOT);if(!baseUrl.contains("§FUZZ§")&&!baseBody.contains("§FUZZ§")&&!baseHeaders.contains("§FUZZ§")){Toast.makeText(this,"Add §FUZZ§ marker",Toast.LENGTH_SHORT).show();return;}if(!Arrays.asList("GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS").contains(baseMethod)){Toast.makeText(this,"Unsupported HTTP method",Toast.LENGTH_SHORT).show();return;}ArrayList<String>ps=new ArrayList<>();for(String x:payloads.getText().toString().split("\\r?\\n")){x=x.trim();if(!x.isEmpty())ps.add(x);if(ps.size()>=50)break;}if(ps.isEmpty()){Toast.makeText(this,"Add payloads",Toast.LENGTH_SHORT).show();return;}stop=false;out.setText("");exec.submit(()->{for(int i=0;i<ps.size()&&!stop;i++){String p=ps.get(i);RequestRecord q=new RequestRecord();q.method=baseMethod;q.url=baseUrl.replace("§FUZZ§",p);q.requestBody=baseBody.replace("§FUZZ§",p);try{for(String line:baseHeaders.split("\\r?\\n")){if(line.trim().isEmpty())continue;int c=line.indexOf(':');if(c>0)q.requestHeaders.put(line.substring(0,c).trim(),line.substring(c+1).trim().replace("§FUZZ§",p));}}catch(Exception ignored){}RequestRecord rr=RequestExecutor.execute(RuleRepository.apply(q),false);String result=(i+1)+"\t"+p+"\t"+rr.statusCode+"\t"+rr.responseBody.length()+" B\t"+rr.durationMs+" ms\n";runOnUiThread(()->out.append(result));try{Thread.sleep(250);}catch(InterruptedException e){Thread.currentThread().interrupt();break;}}});}
 @Override protected void onDestroy(){stop=true;exec.shutdownNow();super.onDestroy();}
}
