package com.reqlens.app;
import android.app.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;
public final class IntruderActivity extends Activity{
 private final ExecutorService exec=Executors.newSingleThreadExecutor();private EditText method,url,headers,body,payloads,grep,rate;private TextView out,summary;private volatile boolean stop;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Request Variations");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);TextView n=new TextView(this);n.setText("Authorized testing only. Use §FUZZ§. Hard safety limits: 50 payloads, one worker, max 4 req/s. No credential-stuffing automation.");r.addView(n);method=e("Method",1);method.setText("GET");r.addView(method);url=e("https://example.test/item?id=§FUZZ§",1);r.addView(url);headers=e("Headers, one per line",2);r.addView(headers);body=e("Body (optional)",2);r.addView(body);payloads=e("Payloads, one per line (max 50)",4);r.addView(payloads);LinearLayout opts=new LinearLayout(this);grep=e("Grep-match text (optional)",1);opts.addView(grep,new LinearLayout.LayoutParams(0,48,2));rate=e("req/s 1-4",1);rate.setText("4");opts.addView(rate,new LinearLayout.LayoutParams(0,48,1));r.addView(opts);LinearLayout row=new LinearLayout(this);Button run=new Button(this);run.setText("RUN");run.setOnClickListener(v->run());row.addView(run,new LinearLayout.LayoutParams(0,48,1));Button st=new Button(this);st.setText("STOP");st.setOnClickListener(v->stop=true);row.addView(st,new LinearLayout.LayoutParams(0,48,1));r.addView(row);summary=new TextView(this);summary.setText("Ready");r.addView(summary);out=new TextView(this);out.setTypeface(Typeface.MONOSPACE);out.setTextIsSelectable(true);ScrollView s=new ScrollView(this);s.addView(out);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private EditText e(String h,int lines){EditText x=new EditText(this);x.setHint(h);x.setMinLines(lines);return x;}
 private void run(){String baseUrl=url.getText().toString().trim(),baseBody=body.getText().toString(),baseHeaders=headers.getText().toString(),baseMethod=method.getText().toString().trim().toUpperCase(Locale.ROOT),match=grep.getText().toString();if(!baseUrl.contains("§FUZZ§")&&!baseBody.contains("§FUZZ§")&&!baseHeaders.contains("§FUZZ§")){toast("Add §FUZZ§ marker");return;}if(!Arrays.asList("GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS").contains(baseMethod)){toast("Unsupported HTTP method");return;}int rps;try{rps=Math.max(1,Math.min(4,Integer.parseInt(rate.getText().toString().trim())));}catch(Exception e){rps=4;}ArrayList<String>ps=new ArrayList<>();for(String x:payloads.getText().toString().split("\\r?\\n")){x=x.trim();if(!x.isEmpty())ps.add(x);if(ps.size()>=50)break;}if(ps.isEmpty()){toast("Add payloads");return;}final int delay=1000/rps;stop=false;out.setText("#\tpayload\tstatus\tbytes\ttime\tmatch\n");summary.setText("Running "+ps.size()+" variations at "+rps+" req/s max");exec.submit(()->{int hits=0,errors=0;for(int i=0;i<ps.size()&&!stop;i++){String p=ps.get(i);RequestRecord q=new RequestRecord();q.method=baseMethod;q.url=baseUrl.replace("§FUZZ§",p);q.requestBody=baseBody.replace("§FUZZ§",p);for(String line:baseHeaders.split("\\r?\\n")){if(line.trim().isEmpty())continue;int c=line.indexOf(':');if(c>0)q.requestHeaders.put(line.substring(0,c).trim(),line.substring(c+1).trim().replace("§FUZZ§",p));}RequestRecord rr=RequestExecutor.execute(RuleRepository.apply(q),false);ProxyHistoryRepository.addHttp(rr,"variations");boolean hit=!match.isEmpty()&&rr.responseBody.contains(match);if(hit)hits++;if(rr.statusCode<0||rr.statusCode>=400)errors++;String result=(i+1)+"\t"+p+"\t"+rr.statusCode+"\t"+rr.responseBody.length()+"\t"+rr.durationMs+"ms\t"+(hit?"YES":"-")+"\n";int done=i+1,fh=hits,fe=errors;runOnUiThread(()->{out.append(result);summary.setText("Completed "+done+" / "+ps.size()+" • matches "+fh+" • errors "+fe);});try{Thread.sleep(delay);}catch(InterruptedException e){Thread.currentThread().interrupt();break;}}});}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 @Override protected void onDestroy(){stop=true;exec.shutdownNow();super.onDestroy();}
}
