package com.reqlens.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.net.Uri;import android.os.Bundle;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.*;
public final class IntruderActivity extends Activity{
 private static final int IMPORT_WORDLIST=551;private final ExecutorService exec=Executors.newSingleThreadExecutor();private EditText method,url,headers,body,payloads,payloadsB,grep,rate;private Spinner mode;private TextView out,summary;private volatile boolean stop;private static final class P{final String a,b;P(String x,String y){a=x;b=y;}}
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Request Variations");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);TextView n=new TextView(this);n.setText("Authorized testing only. Hard limits: 50 total requests, one worker, max 4 req/s. SNIPER uses §FUZZ§; paired modes use §A§ and §B§. No credential-stuffing automation.");r.addView(n);method=e("Method",1);method.setText("GET");r.addView(method);url=e("https://example.test/item?id=§FUZZ§",1);r.addView(url);headers=e("Headers, one per line",2);r.addView(headers);body=e("Body (optional)",2);r.addView(body);mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"SNIPER","PITCHFORK","CLUSTER"}));r.addView(mode);payloads=e("Payload set A / SNIPER payloads (max 50)",4);r.addView(payloads);payloadsB=e("Payload set B for PITCHFORK / CLUSTER",3);r.addView(payloadsB);LinearLayout gen=new LinearLayout(this);add(gen,"NUMBERS",v->numbers());add(gen,"DATES",v->dates());add(gen,"IMPORT",v->pickWordlist());r.addView(gen);LinearLayout opts=new LinearLayout(this);grep=e("Grep-match text (optional)",1);opts.addView(grep,new LinearLayout.LayoutParams(0,48,2));rate=e("req/s 1-4",1);rate.setText("4");opts.addView(rate,new LinearLayout.LayoutParams(0,48,1));r.addView(opts);LinearLayout row=new LinearLayout(this);add(row,"RUN",v->run());add(row,"STOP",v->stop=true);r.addView(row);summary=new TextView(this);summary.setText("Ready");r.addView(summary);out=new TextView(this);out.setTypeface(Typeface.MONOSPACE);out.setTextIsSelectable(true);ScrollView s=new ScrollView(this);s.addView(out);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private EditText e(String h,int lines){EditText x=new EditText(this);x.setHint(h);x.setMinLines(lines);return x;}private void add(LinearLayout row,String text,View.OnClickListener l){Button b=new Button(this);b.setText(text);b.setOnClickListener(l);row.addView(b,new LinearLayout.LayoutParams(0,48,1));}
 private void numbers(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText a=e("Start",1),b=e("End",1),step=e("Step",1);a.setText("1");b.setText("10");step.setText("1");x.addView(a);x.addView(b);x.addView(step);new AlertDialog.Builder(this).setTitle("Numeric payloads").setView(x).setPositiveButton("GENERATE",(d,w)->{try{int s=Integer.parseInt(a.getText().toString()),end=Integer.parseInt(b.getText().toString()),st=Math.max(1,Math.abs(Integer.parseInt(step.getText().toString())));StringBuilder z=new StringBuilder();int count=0;if(s<=end){for(int i=s;i<=end&&count<50;i+=st,count++)z.append(i).append('\n');}else{for(int i=s;i>=end&&count<50;i-=st,count++)z.append(i).append('\n');}payloads.setText(z.toString());}catch(Exception ex){toast("Invalid numeric range");}}).setNegativeButton("CANCEL",null).show();}
 private void dates(){SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd",Locale.ROOT);Calendar c=Calendar.getInstance();StringBuilder z=new StringBuilder();for(int i=-7;i<=7;i++){Calendar q=(Calendar)c.clone();q.add(Calendar.DAY_OF_YEAR,i);z.append(f.format(q.getTime())).append('\n');}payloads.setText(z.toString());}
 private void pickWordlist(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("text/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT_WORDLIST);}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=IMPORT_WORDLIST||result!=RESULT_OK||data==null||data.getData()==null)return;try{payloads.setText(readLines(data.getData()));}catch(Exception e){toast("Import failed: "+e.getMessage());}}
 private String readLines(Uri u)throws Exception{StringBuilder s=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(u),StandardCharsets.UTF_8))){String line;int n=0;while((line=r.readLine())!=null&&n<50){line=line.trim();if(!line.isEmpty()){s.append(line).append('\n');n++;}}}return s.toString();}
 private ArrayList<String>lines(EditText e){ArrayList<String>x=new ArrayList<>();for(String q:e.getText().toString().split("\\r?\\n")){q=q.trim();if(!q.isEmpty())x.add(q);if(x.size()>=50)break;}return x;}
 private ArrayList<P>pairs(String m){ArrayList<String>a=lines(payloads),b=lines(payloadsB);ArrayList<P>out=new ArrayList<>();if("SNIPER".equals(m)){for(String x:a){out.add(new P(x,""));if(out.size()>=50)break;}}else if("PITCHFORK".equals(m)){int n=Math.min(a.size(),b.size());for(int i=0;i<n&&out.size()<50;i++)out.add(new P(a.get(i),b.get(i)));}else{for(String x:a)for(String y:b){out.add(new P(x,y));if(out.size()>=50)return out;}}return out;}
 private void run(){String baseUrl=url.getText().toString().trim(),baseBody=body.getText().toString(),baseHeaders=headers.getText().toString(),baseMethod=method.getText().toString().trim().toUpperCase(Locale.ROOT),match=grep.getText().toString(),m=String.valueOf(mode.getSelectedItem());if("SNIPER".equals(m)){if(!containsAny(baseUrl,baseBody,baseHeaders,"§FUZZ§")){toast("Add §FUZZ§ marker");return;}}else if(!(containsAny(baseUrl,baseBody,baseHeaders,"§A§")&&containsAny(baseUrl,baseBody,baseHeaders,"§B§"))){toast("Paired modes require both §A§ and §B§ markers");return;}if(!Arrays.asList("GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS").contains(baseMethod)){toast("Unsupported HTTP method");return;}int rps;try{rps=Math.max(1,Math.min(4,Integer.parseInt(rate.getText().toString().trim())));}catch(Exception e){rps=4;}ArrayList<P>ps=pairs(m);if(ps.isEmpty()){toast("Add payloads");return;}final int delay=1000/rps;stop=false;out.setText("#\tpayload\tstatus\tbytes\ttime\tmatch\n");summary.setText("Running "+ps.size()+" "+m+" requests at "+rps+" req/s max");exec.submit(()->{int hits=0,errors=0,limited=0;for(int i=0;i<ps.size()&&!stop;i++){P p=ps.get(i);RequestRecord q=new RequestRecord();q.method=baseMethod;q.url=sub(baseUrl,m,p);q.requestBody=sub(baseBody,m,p);for(String line:baseHeaders.split("\\r?\\n")){if(line.trim().isEmpty())continue;int c=line.indexOf(':');if(c>0)q.requestHeaders.put(line.substring(0,c).trim(),sub(line.substring(c+1).trim(),m,p));}RequestRecord rr=RequestExecutor.execute(RuleRepository.apply(q),false);ProxyHistoryRepository.addHttp(rr,"variations");boolean hit=!match.isEmpty()&&rr.responseBody.contains(match);if(hit)hits++;if(rr.statusCode<0||rr.statusCode>=400)errors++;long sleep=delay;if(rr.statusCode==429){limited++;sleep=Math.max(delay,retryAfterMs(rr));}String label="SNIPER".equals(m)?p.a:p.a+" | "+p.b;String result=(i+1)+"\t"+label+"\t"+rr.statusCode+"\t"+rr.responseBody.length()+"\t"+rr.durationMs+"ms\t"+(hit?"YES":"-")+(rr.statusCode==429?" RATE_LIMIT":"")+"\n";int done=i+1,fh=hits,fe=errors,fl=limited;runOnUiThread(()->{out.append(result);summary.setText("Completed "+done+" / "+ps.size()+" • matches "+fh+" • errors "+fe+" • 429s "+fl);});try{Thread.sleep(Math.min(5000,sleep));}catch(InterruptedException e){Thread.currentThread().interrupt();break;}}});}
 private boolean containsAny(String a,String b,String c,String marker){return a.contains(marker)||b.contains(marker)||c.contains(marker);}private String sub(String s,String m,P p){return"SNIPER".equals(m)?s.replace("§FUZZ§",p.a):s.replace("§A§",p.a).replace("§B§",p.b);}
 private long retryAfterMs(RequestRecord r){for(Map.Entry<String,String>e:r.responseHeaders.entrySet())if("Retry-After".equalsIgnoreCase(e.getKey()))try{return Math.max(1000,Long.parseLong(e.getValue().trim())*1000L);}catch(Exception ignored){}return 2000;}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}@Override protected void onDestroy(){stop=true;exec.shutdownNow();super.onDestroy();}
}
