package com.reqlens.app;

import android.app.*;import android.content.*;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

public final class MitmHistoryActivity extends Activity{
 private final ArrayList<RequestRecord>items=new ArrayList<>();private ArrayAdapter<RequestRecord>a;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());refresh();}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(12,12,12,12);TextView t=new TextView(this);t.setText("Decrypted HTTPS History");t.setTextSize(22);r.addView(t);TextView n=new TextView(this);n.setText("Plaintext captured by the ReqLens-authorized local MITM proxy. Sensitive values may be present.");r.addView(n);ListView l=new ListView(this);a=new ArrayAdapter<RequestRecord>(this,android.R.layout.simple_list_item_2,android.R.id.text1,items){@Override public View getView(int p,View c,ViewGroup g){View v=super.getView(p,c,g);RequestRecord x=getItem(p);((TextView)v.findViewById(android.R.id.text1)).setText(x.method+"  "+x.statusCode+"  "+x.url);((TextView)v.findViewById(android.R.id.text2)).setText(x.durationMs+" ms • req "+x.requestBody.length()+" chars • resp "+x.responseBody.length()+" chars");return v;}};l.setAdapter(a);l.setOnItemClickListener((p,v,pos,id)->show(items.get(pos)));r.addView(l,new LinearLayout.LayoutParams(-1,0,1));LinearLayout row=new LinearLayout(this);Button ref=new Button(this);ref.setText("REFRESH");ref.setOnClickListener(v->refresh());row.addView(ref,new LinearLayout.LayoutParams(0,50,1));Button clr=new Button(this);clr.setText("CLEAR");clr.setOnClickListener(v->{MitmHistoryRepository.clear();refresh();});row.addView(clr,new LinearLayout.LayoutParams(0,50,1));r.addView(row);return r;}
 private void refresh(){items.clear();items.addAll(MitmHistoryRepository.snapshotNewestFirst());if(a!=null)a.notifyDataSetChanged();}
 private void show(RequestRecord x){StringBuilder h=new StringBuilder();for(Map.Entry<String,String>e:x.requestHeaders.entrySet())h.append(e.getKey()).append(": ").append(e.getValue()).append('\n');StringBuilder rh=new StringBuilder();for(Map.Entry<String,String>e:x.responseHeaders.entrySet())rh.append(e.getKey()).append(": ").append(e.getValue()).append('\n');String m=x.method+" "+x.url+"\n\nREQUEST HEADERS\n"+h+"\nREQUEST BODY\n"+x.requestBody+"\n\nRESPONSE "+x.statusCode+" "+x.statusText+"\n"+rh+"\n"+x.responseBody;new AlertDialog.Builder(this).setTitle("Decrypted request").setMessage(m).setPositiveButton("REPEATER",(d,w)->{RepeaterActivity.pending=x;startActivity(new Intent(this,RepeaterActivity.class));}).setNegativeButton("CLOSE",null).show();}
}
