package com.reqlens.app;

import android.app.*;import android.content.*;import android.os.Bundle;import android.security.KeyChain;import android.view.*;import android.widget.*;import java.security.cert.X509Certificate;

public final class MitmActivity extends Activity{
 private TextView status;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());refresh();}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(16),dp(16),dp(16),dp(16));TextView t=new TextView(this);t.setText("Authorized HTTPS MITM");t.setTextSize(22);r.addView(t);TextView n=new TextView(this);n.setText("For traffic you own or are explicitly authorized to test. ReqLens creates a local CA and decrypts only clients that explicitly trust that CA. It does not bypass certificate pinning, mTLS, or third-party app protections.");n.setPadding(0,dp(8),0,dp(12));r.addView(n);status=new TextView(this);r.addView(status);Button gen=new Button(this);gen.setText("GENERATE / INSTALL REQLENS CA");gen.setOnClickListener(v->installCa());r.addView(gen,new LinearLayout.LayoutParams(-1,dp(52)));Button start=new Button(this);start.setText("ENABLE MITM FOR REQLENS BROWSER");start.setOnClickListener(v->enable());r.addView(start,new LinearLayout.LayoutParams(-1,dp(52)));Button stop=new Button(this);stop.setText("DISABLE MITM");stop.setOnClickListener(v->disable());r.addView(stop,new LinearLayout.LayoutParams(-1,dp(52)));Button hist=new Button(this);hist.setText("DECRYPTED HTTPS HISTORY");hist.setOnClickListener(v->startActivity(new Intent(this,MitmHistoryActivity.class)));r.addView(hist,new LinearLayout.LayoutParams(-1,dp(52)));Button browser=new Button(this);browser.setText("OPEN REQLENS BROWSER");browser.setOnClickListener(v->startActivity(new Intent(this,BrowserActivity.class)));r.addView(browser,new LinearLayout.LayoutParams(-1,dp(52)));return r;}
 private void installCa(){try{MitmCaManager ca=new MitmCaManager(this);byte[] der=ca.caDer();Intent i=KeyChain.createInstallIntent();i.putExtra(KeyChain.EXTRA_CERTIFICATE,der);i.putExtra(KeyChain.EXTRA_NAME,"ReqLens Authorized MITM CA");startActivity(i);status.setText("CA installer opened. Android requires your explicit approval.");}catch(Exception e){status.setText("CA generation failed: "+e.getClass().getSimpleName()+": "+safe(e.getMessage()));}}
 private void enable(){try{MitmProxyController.setEnabled(this,true);if(!MitmProxyController.proxyOverrideSupported()){status.setText("WebView proxy override is not supported by this WebView build.");return;}int port=MitmProxyController.ensureStarted(this);MitmProxyController.applyToWebViewProcess(this,()->runOnUiThread(this::refresh));status.setText("MITM proxy starting on 127.0.0.1:"+port+". Install/trust the ReqLens CA before browsing HTTPS.");}catch(Exception e){MitmProxyController.setEnabled(this,false);status.setText("MITM start failed: "+e.getClass().getSimpleName()+": "+safe(e.getMessage()));}}
 private void disable(){MitmProxyController.setEnabled(this,false);MitmProxyController.clear(()->{});MitmProxyController.stop(this);refresh();}
 private void refresh(){MitmProxyServer s=MitmProxyServer.get(this);X509Certificate cert=new MitmCaManager(this).loadStoredCertificate();status.setText("Enabled: "+MitmProxyController.enabled(this)+"\nProxy: "+(s.isRunning()?"127.0.0.1:"+s.port():"stopped")+"\nWebView proxy override: "+MitmProxyController.proxyOverrideSupported()+"\nCA generated: "+(cert!=null)+"\nDecrypted records: "+MitmHistoryRepository.size()+(s.lastError().isEmpty()?"":"\nLast proxy error: "+s.lastError()));}
 private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private static String safe(String s){return s==null?"unknown":s;}
}
