package com.reqlens.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.net.Uri;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
public final class ProjectsActivity extends Activity{
 private static final int IMPORT_REQ=441;private final ArrayList<ProjectRepository.Project>items=new ArrayList<>();private ArrayAdapter<ProjectRepository.Project>a;
 @Override public void onCreate(Bundle b){super.onCreate(b);ProjectRepository.init(this);BrowserHistoryRepository.init(this);ProxyHistoryRepository.init(this);setContentView(ui());refresh();}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Projects");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);TextView active=new TextView(this);active.setId(12345);r.addView(active);LinearLayout row=new LinearLayout(this);Button add=new Button(this);add.setText("NEW PROJECT");add.setOnClickListener(v->newProject());row.addView(add,new LinearLayout.LayoutParams(0,48,1));Button imp=new Button(this);imp.setText("IMPORT PROJECT");imp.setOnClickListener(v->pickImport());row.addView(imp,new LinearLayout.LayoutParams(0,48,1));r.addView(row);ListView l=new ListView(this);a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,items);l.setAdapter(a);l.setOnItemClickListener((p,v,pos,id)->{ProjectRepository.activate(items.get(pos).id);refresh();});r.addView(l,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private void newProject(){EditText e=new EditText(this);e.setHint("Project name");new AlertDialog.Builder(this).setTitle("New project").setView(e).setPositiveButton("CREATE",(d,w)->{String n=e.getText().toString().trim();if(n.isEmpty())n="Project "+System.currentTimeMillis();ProjectRepository.add(n);refresh();}).setNegativeButton("CANCEL",null).show();}
 private void pickImport(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT_REQ);}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=IMPORT_REQ||result!=RESULT_OK||data==null||data.getData()==null)return;try{String raw=read(data.getData());JSONObject o=new JSONObject(raw);if(!"ReqLensWorkspace".equals(o.optString("format")))throw new IllegalArgumentException("Not a ReqLens workspace export");String name=o.optString("projectName","Imported project")+" (imported)";ProjectRepository.Project p=ProjectRepository.add(name);int b=BrowserHistoryRepository.importItems(o.optJSONArray("browser"),p.id);int x=ProxyHistoryRepository.importItems(o.optJSONArray("proxy"),p.id);refresh();Toast.makeText(this,"Imported "+b+" browser + "+x+" proxy records",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Import failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private String read(Uri u)throws Exception{try(InputStream in=getContentResolver().openInputStream(u);ByteArrayOutputStream out=new ByteArrayOutputStream()){if(in==null)throw new IOException("Cannot open file");byte[]b=new byte[8192];int n,total=0;while((n=in.read(b))!=-1){total+=n;if(total>5_000_000)throw new IOException("Workspace file too large");out.write(b,0,n);}return out.toString(StandardCharsets.UTF_8.name());}}
 private void refresh(){items.clear();items.addAll(ProjectRepository.snapshot());if(a!=null)a.notifyDataSetChanged();TextView t=findViewById(12345);if(t!=null)t.setText("Active: "+ProjectRepository.active().name+" • histories are isolated by project");}
}
