package com.reqlens.app;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

public final class ProxyHistoryActivity extends Activity {
    private final ArrayList<ProxyEvent> items=new ArrayList<>(); private ArrayAdapter<ProxyEvent> adapter; private EditText filter;
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());refresh();}
    private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Proxy History");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);TextView n=new TextView(this);n.setText("Live capture metadata + HTTP requests sent through ReqLens. Encrypted app traffic stays metadata-only unless you use an authorized debug integration.");r.addView(n);LinearLayout row=new LinearLayout(this);filter=new EditText(this);filter.setHint("Filter host / app / protocol / URL");row.addView(filter,new LinearLayout.LayoutParams(0,48,1));Button f=new Button(this);f.setText("REFRESH");f.setOnClickListener(v->refresh());row.addView(f,new LinearLayout.LayoutParams(110,48));r.addView(row);ListView list=new ListView(this);adapter=new ArrayAdapter<ProxyEvent>(this,android.R.layout.simple_list_item_2,android.R.id.text1,items){@Override public View getView(int p,View c,ViewGroup g){View v=super.getView(p,c,g);ProxyEvent e=getItem(p);((TextView)v.findViewById(android.R.id.text1)).setText(e.toString());((TextView)v.findViewById(android.R.id.text2)).setText(detail(e));return v;}};list.setAdapter(adapter);list.setOnItemClickListener((a,v,p,id)->show(items.get(p)));r.addView(list,new LinearLayout.LayoutParams(-1,0,1));Button clear=new Button(this);clear.setText("CLEAR PROXY HISTORY");clear.setOnClickListener(v->{ProxyHistoryRepository.clear();refresh();});r.addView(clear);return r;}
    private void refresh(){String q=filter==null?"":filter.getText().toString().trim().toLowerCase(Locale.ROOT);items.clear();for(ProxyEvent e:ProxyHistoryRepository.snapshotNewestFirst()){String hay=(e.protocol+" "+e.host+" "+e.ip+" "+e.appLabel+" "+e.appPackage+" "+e.method+" "+e.url+" "+e.tlsSni).toLowerCase(Locale.ROOT);if(q.isEmpty()||hay.contains(q))items.add(e);}if(adapter!=null)adapter.notifyDataSetChanged();}
    private String detail(ProxyEvent e){String tls=e.tlsSni.isEmpty()?"":" • SNI "+e.tlsSni+(e.tlsAlpn.isEmpty()?"":" • "+e.tlsAlpn);return (e.status>=0?"HTTP "+e.status+" • ":"")+e.bytes+" B"+tls;}
    private void show(ProxyEvent e){String m="Source: "+e.source+"\nProtocol: "+e.protocol+"\nHost: "+e.host+"\nIP: "+e.ip+":"+e.port+"\nApp: "+e.appLabel+"\nPackage: "+e.appPackage+"\nTLS SNI: "+e.tlsSni+"\nALPN: "+e.tlsAlpn+"\nTLS: "+e.tlsVersion+"\nBytes: "+e.bytes+(e.url.isEmpty()?"":"\nURL: "+e.url);new AlertDialog.Builder(this).setTitle("Proxy event").setMessage(m).setPositiveButton("OK",null).show();}
}
