package com.reqlens.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;
public final class RepeaterActivity extends Activity{
 public static RequestRecord pending;private final ExecutorService exec=Executors.newSingleThreadExecutor();private Spinner tabs,method;private ArrayAdapter<RepeaterTabRepository.Tab>tabAdapter;private RepeaterTabRepository.Tab tab;private EditText url,headers,body;private TextView result,status;private boolean loading;
 @Override public void onCreate(Bundle b){super.onCreate(b);tab=pending!=null?RepeaterTabRepository.open(pending):RepeaterTabRepository.ensure();pending=null;setContentView(ui());refreshTabs();select(tab);}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("ReqLens Repeater");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);LinearLayout tr=new LinearLayout(this);tabs=new Spinner(this);tabAdapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new ArrayList<>());tabs.setAdapter(tabAdapter);tabs.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(loading)return;saveCurrent();List<RepeaterTabRepository.Tab>x=RepeaterTabRepository.snapshot();if(pos>=0&&pos<x.size())select(x.get(pos));}public void onNothingSelected(AdapterView<?>p){}});tr.addView(tabs,new LinearLayout.LayoutParams(0,46,1));add(tr,"+",v->{saveCurrent();select(RepeaterTabRepository.open(new RequestRecord()));refreshTabs();});add(tr,"DUP",v->{saveCurrent();select(RepeaterTabRepository.duplicate(tab));refreshTabs();});add(tr,"×",v->{long id=tab.id;RepeaterTabRepository.close(id);refreshTabs();List<RepeaterTabRepository.Tab>x=RepeaterTabRepository.snapshot();select(x.get(Math.max(0,x.size()-1)));});r.addView(tr);status=new TextView(this);status.setText("Editable authorized request workspace");r.addView(status);method=new Spinner(this);method.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS"}));r.addView(method);url=new EditText(this);url.setHint("URL");r.addView(url);headers=new EditText(this);headers.setHint("Headers, one per line");headers.setMinLines(3);headers.setTypeface(Typeface.MONOSPACE);r.addView(headers);body=new EditText(this);body.setHint("Body");body.setMinLines(4);body.setTypeface(Typeface.MONOSPACE);r.addView(body);LinearLayout a=new LinearLayout(this);add(a,"SEND",v->send());add(a,"RAW",v->raw());add(a,"PRETTY",v->pretty());add(a,"DIFF",v->showDiff());r.addView(a);LinearLayout b=new LinearLayout(this);add(b,"HISTORY",v->showHistory());add(b,"REQ DIFF",v->showRequestDiff());add(b,"BODY TOOLS",v->{BodyToolsActivity.pendingBody=body.getText().toString();startActivity(new Intent(this,BodyToolsActivity.class));});add(b,"MULTI",v->startActivity(new Intent(this,MultiResponseCompareActivity.class)));add(b,"COMPARE",v->{ComparerActivity.left=tab.baseline==null?"":tab.baseline.responseBody;ComparerActivity.right=tab.last==null?"":tab.last.responseBody;startActivity(new Intent(this,ComparerActivity.class));});r.addView(b);result=new TextView(this);result.setTextIsSelectable(true);result.setTypeface(Typeface.MONOSPACE);ScrollView s=new ScrollView(this);s.addView(result);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private void add(LinearLayout row,String text,View.OnClickListener l){Button b=new Button(this);b.setText(text);b.setOnClickListener(l);row.addView(b,new LinearLayout.LayoutParams(0,48,1));}
 private void refreshTabs(){loading=true;List<RepeaterTabRepository.Tab>x=RepeaterTabRepository.snapshot();tabAdapter.clear();tabAdapter.addAll(x);tabAdapter.notifyDataSetChanged();if(tab!=null){int i=x.indexOf(tab);if(i>=0)tabs.setSelection(i);}loading=false;}
 private void select(RepeaterTabRepository.Tab t){if(t==null)return;tab=t;load(t.request);if(t.last!=null){status.setText((t.last.statusCode<0?"ERR":t.last.statusCode)+" • "+t.last.durationMs+" ms");result.setText(RawHttpFormatter.response(t.last));}else{status.setText("Ready");result.setText("");}refreshTabs();}
 private void saveCurrent(){if(tab==null||loading||url==null)return;try{tab.request=collect();RepeaterTabRepository.rename(tab);}catch(Exception ignored){}}
 private void load(RequestRecord x){loading=true;String[]m={"GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS"};for(int i=0;i<m.length;i++)if(m[i].equals(x.method))method.setSelection(i);url.setText(x.url);StringBuilder h=new StringBuilder();for(Map.Entry<String,String>e:x.requestHeaders.entrySet())h.append(e.getKey()).append(": ").append(e.getValue()).append('\n');headers.setText(h.toString());body.setText(x.requestBody);loading=false;}
 private RequestRecord collect(){RequestRecord q=new RequestRecord();q.method=String.valueOf(method.getSelectedItem());q.url=url.getText().toString().trim();q.requestBody=body.getText().toString();for(String line:headers.getText().toString().split("\\r?\\n")){if(line.trim().isEmpty())continue;int c=line.indexOf(':');if(c<=0)throw new IllegalArgumentException("Bad header: "+line);q.requestHeaders.put(line.substring(0,c).trim(),line.substring(c+1).trim());}if(!(q.url.startsWith("https://")||q.url.startsWith("http://")))throw new IllegalArgumentException("URL must use HTTP/HTTPS");return q;}
 private void send(){final RequestRecord q;try{q=collect();}catch(Exception e){toast(e.getMessage());return;}tab.request=RequestExecutor.cloneRequest(q);RepeaterTabRepository.rename(tab);refreshTabs();status.setText("Sending…");final RepeaterTabRepository.Tab target=tab;exec.submit(()->{RequestRecord rr=RequestExecutor.execute(RuleRepository.apply(q),false);target.last=rr;target.history.add(0,rr);while(target.history.size()>30)target.history.remove(target.history.size()-1);ProxyHistoryRepository.addHttp(rr,"repeater");runOnUiThread(()->{if(tab==target){status.setText((rr.statusCode<0?"ERR":rr.statusCode)+" • "+rr.durationMs+" ms • "+rr.responseBody.length()+" B");result.setText(RawHttpFormatter.response(rr));}});});}
 private void raw(){try{RequestRecord q=collect();String text=RawHttpFormatter.request(q)+(tab.last==null?"":"\n\n--- RESPONSE ---\n"+RawHttpFormatter.response(tab.last));new AlertDialog.Builder(this).setTitle("Raw HTTP").setMessage(text).setPositiveButton("OK",null).show();}catch(Exception e){toast(e.getMessage());}}
 private void pretty(){String x=body.getText().toString().trim();try{if(x.startsWith("{"))body.setText(new JSONObject(x).toString(2));else if(x.startsWith("["))body.setText(new JSONArray(x).toString(2));else if(x.startsWith("<"))body.setText(XmlFormatter.pretty(x));else toast("Body is not JSON/XML");}catch(Exception e){toast("Invalid structured body");}}

 private void showRequestDiff(){try{RequestRecord now=collect();String a=RawHttpFormatter.request(tab.baseline),b=RawHttpFormatter.request(now);new AlertDialog.Builder(this).setTitle("Request diff vs original").setMessage(TextDiff.summarize(a,b)).setPositiveButton("OK",null).show();}catch(Exception e){toast(e.getMessage());}}
 private void showDiff(){if(tab.last==null){toast("Send a request first");return;}new AlertDialog.Builder(this).setTitle("Response analysis vs original").setMessage(ResponseAnalyzer.compare(tab.baseline,tab.last)).setPositiveButton("OK",null).show();}
 private void showHistory(){if(tab.history.isEmpty()){toast("No history for this tab");return;}String[]a=new String[tab.history.size()];for(int i=0;i<a.length;i++){RequestRecord x=tab.history.get(i);a[i]=(x.statusCode<0?"ERR":x.statusCode)+" • "+x.durationMs+" ms • "+x.method+" "+x.url;}new AlertDialog.Builder(this).setTitle("Tab history").setItems(a,(d,w)->{tab.last=tab.history.get(w);result.setText(RawHttpFormatter.response(tab.last));}).setNegativeButton("CLOSE",null).show();}
 private void toast(String s){Toast.makeText(this,s==null?"Error":s,Toast.LENGTH_SHORT).show();}
 @Override protected void onResume(){super.onResume();if(BodyToolsActivity.resultBody!=null&&body!=null){body.setText(BodyToolsActivity.resultBody);BodyToolsActivity.resultBody=null;saveCurrent();}}
 @Override protected void onDestroy(){saveCurrent();exec.shutdownNow();super.onDestroy();}
}
