package com.reqlens.app;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.JSONObject;import java.util.*;import java.util.concurrent.*;

public final class RepeaterActivity extends Activity {
    public static RequestRecord pending; private final ExecutorService exec=Executors.newSingleThreadExecutor(); private Spinner method; private EditText url,headers,body; private TextView result; private RequestRecord baseline,last;
    @Override public void onCreate(Bundle b){super.onCreate(b);baseline=pending==null?new RequestRecord():pending; pending=null;setContentView(ui());load(baseline);}
    private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("ReqLens Repeater");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);method=new Spinner(this);method.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS"}));r.addView(method);url=new EditText(this);url.setHint("URL");r.addView(url);headers=new EditText(this);headers.setHint("Headers");headers.setMinLines(3);r.addView(headers);body=new EditText(this);body.setHint("Body");body.setMinLines(4);body.setTypeface(Typeface.MONOSPACE);r.addView(body);LinearLayout a=new LinearLayout(this);Button send=new Button(this);send.setText("SEND AGAIN");send.setOnClickListener(v->send());a.addView(send,new LinearLayout.LayoutParams(0,50,1));Button diff=new Button(this);diff.setText("DIFF");diff.setOnClickListener(v->showDiff());a.addView(diff,new LinearLayout.LayoutParams(0,50,1));r.addView(a);result=new TextView(this);result.setTextIsSelectable(true);result.setTypeface(Typeface.MONOSPACE);ScrollView s=new ScrollView(this);s.addView(result);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));return r;}
    private void load(RequestRecord x){String[]m={"GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS"};for(int i=0;i<m.length;i++)if(m[i].equals(x.method))method.setSelection(i);url.setText(x.url);StringBuilder h=new StringBuilder();for(Map.Entry<String,String>e:x.requestHeaders.entrySet())h.append(e.getKey()).append(": ").append(e.getValue()).append('\n');headers.setText(h.toString());body.setText(x.requestBody);}
    private void send(){RequestRecord q=new RequestRecord();q.method=String.valueOf(method.getSelectedItem());q.url=url.getText().toString().trim();q.requestBody=body.getText().toString();try{for(String line:headers.getText().toString().split("\\r?\\n")){if(line.trim().isEmpty())continue;int c=line.indexOf(':');if(c<=0)throw new IllegalArgumentException("Bad header: "+line);q.requestHeaders.put(line.substring(0,c).trim(),line.substring(c+1).trim());}}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_SHORT).show();return;}result.setText("Sending…");exec.submit(()->{RequestRecord rr=RequestExecutor.execute(q,false);last=rr;runOnUiThread(()->result.setText(render(rr)));});}
    private String render(RequestRecord r){StringBuilder s=new StringBuilder();s.append(r.statusCode).append(' ').append(r.statusText).append(" • ").append(r.durationMs).append(" ms\n\n");for(Map.Entry<String,String>e:r.responseHeaders.entrySet())s.append(e.getKey()).append(": ").append(e.getValue()).append('\n');s.append("\n").append(r.responseBody);if(!r.error.isEmpty())s.append("\nERROR: ").append(r.error);return s.toString();}
    private void showDiff(){if(last==null){Toast.makeText(this,"Send a request first",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("Response diff vs original").setMessage(TextDiff.summarize(baseline.responseBody,last.responseBody)).setPositiveButton("OK",null).show();}
    @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
