package com.reqlens.app;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;

public final class RepeaterActivity extends Activity {
 public static RequestRecord pending; private final ExecutorService exec=Executors.newSingleThreadExecutor(); private final ArrayList<RequestRecord> history=new ArrayList<>(); private Spinner method; private EditText url,headers,body; private TextView result,status; private RequestRecord baseline,last;
 @Override public void onCreate(Bundle b){super.onCreate(b);baseline=pending==null?new RequestRecord():RequestExecutor.cloneRequest(pending);pending=null;setContentView(ui());load(baseline);}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("ReqLens Repeater");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);status=new TextView(this);status.setText("Editable authorized request workspace");r.addView(status);method=new Spinner(this);method.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS"}));r.addView(method);url=new EditText(this);url.setHint("URL");r.addView(url);headers=new EditText(this);headers.setHint("Headers, one per line");headers.setMinLines(3);headers.setTypeface(Typeface.MONOSPACE);r.addView(headers);body=new EditText(this);body.setHint("Body");body.setMinLines(4);body.setTypeface(Typeface.MONOSPACE);r.addView(body);LinearLayout a=new LinearLayout(this);add(a,"SEND",v->send());add(a,"RAW",v->raw());add(a,"PRETTY",v->pretty());add(a,"DUP",v->duplicate());r.addView(a);LinearLayout b=new LinearLayout(this);add(b,"DIFF",v->showDiff());add(b,"HISTORY",v->showHistory());add(b,"COMPARE",v->{ComparerActivity.left=baseline.responseBody;ComparerActivity.right=last==null?"":last.responseBody;startActivity(new Intent(this,ComparerActivity.class));});r.addView(b);result=new TextView(this);result.setTextIsSelectable(true);result.setTypeface(Typeface.MONOSPACE);ScrollView s=new ScrollView(this);s.addView(result);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private void add(LinearLayout row,String text,View.OnClickListener l){Button b=new Button(this);b.setText(text);b.setOnClickListener(l);row.addView(b,new LinearLayout.LayoutParams(0,50,1));}
 private void load(RequestRecord x){String[]m={"GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS"};for(int i=0;i<m.length;i++)if(m[i].equals(x.method))method.setSelection(i);url.setText(x.url);StringBuilder h=new StringBuilder();for(Map.Entry<String,String>e:x.requestHeaders.entrySet())h.append(e.getKey()).append(": ").append(e.getValue()).append('\n');headers.setText(h.toString());body.setText(x.requestBody);}
 private RequestRecord collect(){RequestRecord q=new RequestRecord();q.method=String.valueOf(method.getSelectedItem());q.url=url.getText().toString().trim();q.requestBody=body.getText().toString();for(String line:headers.getText().toString().split("\\r?\\n")){if(line.trim().isEmpty())continue;int c=line.indexOf(':');if(c<=0)throw new IllegalArgumentException("Bad header: "+line);q.requestHeaders.put(line.substring(0,c).trim(),line.substring(c+1).trim());}if(!(q.url.startsWith("https://")||q.url.startsWith("http://")))throw new IllegalArgumentException("URL must use HTTP/HTTPS");return q;}
 private void send(){final RequestRecord q;try{q=collect();}catch(Exception e){toast(e.getMessage());return;}status.setText("Sending…");exec.submit(()->{RequestRecord rr=RequestExecutor.execute(RuleRepository.apply(q),false);last=rr;history.add(0,rr);while(history.size()>30)history.remove(history.size()-1);ProxyHistoryRepository.addHttp(rr,"repeater");runOnUiThread(()->{status.setText((rr.statusCode<0?"ERR":rr.statusCode)+" • "+rr.durationMs+" ms • "+rr.responseBody.length()+" B");result.setText(render(rr));});});}
 private String render(RequestRecord r){return RawHttpFormatter.response(r);}
 private void raw(){try{RequestRecord q=collect();String text=RawHttpFormatter.request(q)+(last==null?"":"\n\n--- RESPONSE ---\n"+RawHttpFormatter.response(last));new AlertDialog.Builder(this).setTitle("Raw HTTP").setMessage(text).setPositiveButton("OK",null).show();}catch(Exception e){toast(e.getMessage());}}
 private void pretty(){String x=body.getText().toString().trim();try{if(x.startsWith("{"))body.setText(new JSONObject(x).toString(2));else if(x.startsWith("["))body.setText(new JSONArray(x).toString(2));else toast("Body is not JSON");}catch(Exception e){toast("Invalid JSON");}}
 private void duplicate(){try{pending=collect();startActivity(new Intent(this,RepeaterActivity.class));}catch(Exception e){toast(e.getMessage());}}
 private void showDiff(){if(last==null){toast("Send a request first");return;}new AlertDialog.Builder(this).setTitle("Response diff vs original").setMessage(TextDiff.summarize(baseline.responseBody,last.responseBody)).setPositiveButton("OK",null).show();}
 private void showHistory(){if(history.isEmpty()){toast("No Repeater history yet");return;}String[]a=new String[history.size()];for(int i=0;i<a.length;i++){RequestRecord x=history.get(i);a[i]=(x.statusCode<0?"ERR":x.statusCode)+" • "+x.durationMs+" ms • "+x.method+" "+x.url;}new AlertDialog.Builder(this).setTitle("Repeater history").setItems(a,(d,w)->{last=history.get(w);result.setText(render(last));}).setNegativeButton("CLOSE",null).show();}
 private void toast(String s){Toast.makeText(this,s==null?"Error":s,Toast.LENGTH_SHORT).show();}
 @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
