package com.reqlens.app;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.text.*;import android.view.*;import android.widget.*;import com.google.android.material.card.MaterialCardView;import java.util.*;

public final class ResearchSuiteActivity extends Activity{
 private final ArrayList<Integer> visible=new ArrayList<>();private LinearLayout list;private EditText search;private Spinner group;
 @Override public void onCreate(Bundle b){super.onCreate(b);EvidenceRepository.init(this);setContentView(ui());refresh();}
 private View ui(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(16));TextView t=text("Research Suite",28,true);root.addView(t);TextView s=text("80 integrated research, API, evidence and workflow capabilities. Passive analysis is available immediately; active tests stay bounded and authorization-focused.",13,false);s.setAlpha(.72f);s.setPadding(0,0,0,dp(12));root.addView(s);
  LinearLayout bar=new LinearLayout(this);search=new EditText(this);search.setHint("Search all 80 features");search.setSingleLine(true);bar.addView(search,new LinearLayout.LayoutParams(0,dp(52),1));group=new Spinner(this);ArrayList<String>g=new ArrayList<>();g.add("All");g.addAll(Arrays.asList(FeatureCatalog.GROUPS));group.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,g));bar.addView(group,new LinearLayout.LayoutParams(dp(150),dp(52)));root.addView(bar);
  search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence a,int b,int c,int d){}public void onTextChanged(CharSequence a,int b,int c,int d){refresh();}public void afterTextChanged(Editable e){}});group.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>p,View v,int pos,long id){refresh();}public void onNothingSelected(AdapterView<?>p){}});
  ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));return root;}
 private void refresh(){if(list==null)return;list.removeAllViews();visible.clear();String q=search==null?"":search.getText().toString().trim().toLowerCase(Locale.ROOT);String g=group==null||group.getSelectedItem()==null?"All":String.valueOf(group.getSelectedItem());for(int id=1;id<=80;id++){String n=FeatureCatalog.NAMES[id-1],cat=FeatureCatalog.group(id);if(!"All".equals(g)&&!g.equals(cat))continue;if(!q.isEmpty()&&!n.toLowerCase(Locale.ROOT).contains(q)&&!cat.toLowerCase(Locale.ROOT).contains(q))continue;visible.add(id);list.addView(card(id,n,cat));}TextView count=text(visible.size()+" / 80 capabilities",12,false);count.setAlpha(.55f);list.addView(count);}
 private View card(int id,String name,String cat){MaterialCardView c=new MaterialCardView(this);c.setRadius(dp(18));LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(12));TextView a=text(String.format(Locale.ROOT,"%02d  %s",id,name),17,true);box.addView(a);TextView b=text(cat,12,false);b.setAlpha(.6f);box.addView(b);c.addView(box);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(8));c.setLayoutParams(lp);c.setOnClickListener(v->{Intent i=new Intent(this,FeatureDetailActivity.class);i.putExtra("featureId",id);startActivity(i);});return c;}
 private TextView text(String s,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
