package com.reqlens.app;
import org.json.*;import java.util.*;
public final class ResponseAnalyzer{
 private ResponseAnalyzer(){}
 public static String compare(RequestRecord a,RequestRecord b){StringBuilder s=new StringBuilder();s.append("Status: ").append(a.statusCode).append(" → ").append(b.statusCode).append('\n');s.append("Timing: ").append(a.durationMs).append(" ms → ").append(b.durationMs).append(" ms (Δ ").append(b.durationMs-a.durationMs).append(" ms)\n");int as=a.responseBody==null?0:a.responseBody.length(),bs=b.responseBody==null?0:b.responseBody.length();s.append("Body size: ").append(as).append(" → ").append(bs).append(" (Δ ").append(bs-as).append(")\n");s.append(headerDiff(a.responseHeaders,b.responseHeaders));s.append(cookieDiff(a.responseHeaders,b.responseHeaders));s.append(jsonDiff(a.responseBody,b.responseBody));s.append("\nText diff:\n").append(TextDiff.summarize(a.responseBody,b.responseBody));return s.toString();}
 private static String headerDiff(Map<String,String>a,Map<String,String>b){int added=0,removed=0,changed=0;for(String k:b.keySet()){String ak=getIgnore(a,k);if(ak==null)added++;else if(!Objects.equals(ak,b.get(k)))changed++;}for(String k:a.keySet())if(getIgnore(b,k)==null)removed++;return "Headers: +"+added+" -"+removed+" changed="+changed+"\n";}
 private static String cookieDiff(Map<String,String>a,Map<String,String>b){String x=getIgnore(a,"Set-Cookie"),y=getIgnore(b,"Set-Cookie");if(Objects.equals(x,y))return "Cookies: unchanged\n";return "Cookies: changed\n";}
 private static String jsonDiff(String a,String b){try{JSONObject x=new JSONObject(a),y=new JSONObject(b);Set<String>ka=new TreeSet<>(),kb=new TreeSet<>();x.keys().forEachRemaining(ka::add);y.keys().forEachRemaining(kb::add);Set<String>added=new TreeSet<>(kb);added.removeAll(ka);Set<String>removed=new TreeSet<>(ka);removed.removeAll(kb);int changed=0;for(String k:ka)if(kb.contains(k)&&!Objects.equals(String.valueOf(x.opt(k)),String.valueOf(y.opt(k))))changed++;return "JSON top-level: +"+added+" -"+removed+" changed="+changed+"\n";}catch(Exception e){return "JSON structural diff: n/a\n";}}
 private static String getIgnore(Map<String,String>m,String k){for(Map.Entry<String,String>e:m.entrySet())if(k.equalsIgnoreCase(e.getKey()))return e.getValue();return null;}
}
