package com.reqlens.app;
import android.app.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;
public final class RulesActivity extends Activity{
 private final ArrayList<InterceptRule>items=new ArrayList<>();private ArrayAdapter<InterceptRule>a;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());refresh();}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("Rules Engine");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);TextView n=new TextView(this);n.setText("Ordered request rewrite rules. Tap to enable/disable; long press for actions. Authorized traffic only.");r.addView(n);Button add=new Button(this);add.setText("ADD RULE");add.setOnClickListener(v->dialog());r.addView(add);ListView l=new ListView(this);a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,items);l.setAdapter(a);l.setOnItemClickListener((p,v,pos,id)->{RuleRepository.toggle(pos);refresh();});l.setOnItemLongClickListener((p,v,pos,id)->{actions(pos);return true;});r.addView(l,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private void dialog(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);EditText host=new EditText(this);host.setHint("Host/path contains (optional)");x.addView(host);EditText method=new EditText(this);method.setHint("Method e.g. POST (optional)");x.addView(method);Spinner action=new Spinner(this);action.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"SET_HEADER","REMOVE_HEADER","REPLACE_URL","REPLACE_BODY"}));x.addView(action);EditText name=new EditText(this);name.setHint("Header name / text to find");x.addView(name);EditText value=new EditText(this);value.setHint("Value / replacement");x.addView(value);new AlertDialog.Builder(this).setTitle("New rule").setView(x).setPositiveButton("ADD",(d,w)->{InterceptRule q=new InterceptRule();q.hostContains=host.getText().toString().trim();q.method=method.getText().toString().trim().toUpperCase(Locale.ROOT);q.action=String.valueOf(action.getSelectedItem());q.name=name.getText().toString();q.value=value.getText().toString();RuleRepository.add(q);refresh();}).setNegativeButton("CANCEL",null).show();}
 private void actions(int pos){new AlertDialog.Builder(this).setTitle("Rule actions").setItems(new String[]{"Move up","Move down","Enable / disable","Delete"},(d,w)->{if(w==0)RuleRepository.move(pos,-1);else if(w==1)RuleRepository.move(pos,1);else if(w==2)RuleRepository.toggle(pos);else RuleRepository.remove(pos);refresh();}).show();}
 private void refresh(){items.clear();items.addAll(RuleRepository.snapshot());if(a!=null)a.notifyDataSetChanged();}
}
