package com.reqlens.app;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;
public final class WebSocketHistoryActivity extends Activity{
 private final ArrayList<WebSocketHistoryRepository.Event>items=new ArrayList<>();private ArrayAdapter<WebSocketHistoryRepository.Event>a;private EditText filter;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());refresh();}
 private View ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(16,16,16,16);TextView t=new TextView(this);t.setText("WebSocket History");t.setTextSize(22);t.setTypeface(Typeface.DEFAULT_BOLD);r.addView(t);TextView n=new TextView(this);n.setText("WebSocket upgrade handshakes visible to ReqLens. Passive encrypted frame contents remain opaque.");r.addView(n);LinearLayout row=new LinearLayout(this);filter=new EditText(this);filter.setHint("Filter URL / status");row.addView(filter,new LinearLayout.LayoutParams(0,48,1));Button ref=new Button(this);ref.setText("FILTER");ref.setOnClickListener(v->refresh());row.addView(ref,new LinearLayout.LayoutParams(100,48));r.addView(row);ListView l=new ListView(this);a=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,items);l.setAdapter(a);l.setOnItemClickListener((p,v,pos,id)->show(items.get(pos)));r.addView(l,new LinearLayout.LayoutParams(-1,0,1));Button clear=new Button(this);clear.setText("CLEAR");clear.setOnClickListener(v->{WebSocketHistoryRepository.clear();refresh();});r.addView(clear);return r;}
 private void refresh(){String q=filter==null?"":filter.getText().toString().trim().toLowerCase(Locale.ROOT);items.clear();for(WebSocketHistoryRepository.Event e:WebSocketHistoryRepository.snapshot()){String h=(e.url+" "+e.status+" "+e.note).toLowerCase(Locale.ROOT);if(q.isEmpty()||h.contains(q))items.add(e);}Collections.reverse(items);if(a!=null)a.notifyDataSetChanged();}
 private void show(WebSocketHistoryRepository.Event e){String m="URL: "+e.url+"\nStatus: "+e.status+"\n\nRequest headers:\n"+e.requestHeaders+"\nResponse headers:\n"+e.responseHeaders;new AlertDialog.Builder(this).setTitle("WebSocket handshake").setMessage(m).setPositiveButton("REPEATER",(d,w)->{RequestRecord r=new RequestRecord();r.method="GET";r.url=e.url;r.requestHeaders.put("Connection","Upgrade");r.requestHeaders.put("Upgrade","websocket");RepeaterActivity.pending=r;startActivity(new Intent(this,RepeaterActivity.class));}).setNegativeButton("CLOSE",null).show();}
}
